local LSM = LibStub("LibSharedMedia-3.0")

-- ----------
--   SOUNDS
-- ----------
LSM:Register("sound", "|cff00FF96SoundBox|r: ayaya", [[Interface\Addons\SoundBox\sounds\ayaya.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: badum", [[Interface\Addons\SoundBox\sounds\badum.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: bennyhill", [[Interface\Addons\SoundBox\sounds\bennyhill.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: careless", [[Interface\Addons\SoundBox\sounds\careless.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: circus", [[Interface\Addons\SoundBox\sounds\circus.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: combo", [[Interface\Addons\SoundBox\sounds\combo.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: drama", [[Interface\Addons\SoundBox\sounds\drama.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: finish", [[Interface\Addons\SoundBox\sounds\finish.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: foreveralone", [[Interface\Addons\SoundBox\sounds\foreveralone.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: giorno", [[Interface\Addons\SoundBox\sounds\giorno.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: godno", [[Interface\Addons\SoundBox\sounds\godno.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: goh", [[Interface\Addons\SoundBox\sounds\goh.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: gura", [[Interface\Addons\SoundBox\sounds\gura.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: jeopardy", [[Interface\Addons\SoundBox\sounds\jeopardy.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: kek", [[Interface\Addons\SoundBox\sounds\kek.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: migatte", [[Interface\Addons\SoundBox\sounds\migatte.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: mission", [[Interface\Addons\SoundBox\sounds\mission.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: missioni", [[Interface\Addons\SoundBox\sounds\missioni.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: nani", [[Interface\Addons\SoundBox\sounds\nani.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: nono", [[Interface\Addons\SoundBox\sounds\nono.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: nooo", [[Interface\Addons\SoundBox\sounds\nooo.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: nudge", [[Interface\Addons\SoundBox\sounds\nudge.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: ohbaby", [[Interface\Addons\SoundBox\sounds\ohbaby.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: ohno", [[Interface\Addons\SoundBox\sounds\ohno.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: powaa", [[Interface\Addons\SoundBox\sounds\powaa.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: rezero", [[Interface\Addons\SoundBox\sounds\rezero.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: stars", [[Interface\Addons\SoundBox\sounds\stars.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: tbc", [[Interface\Addons\SoundBox\sounds\tbc.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: titanic", [[Interface\Addons\SoundBox\sounds\titanic.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: tuturu", [[Interface\Addons\SoundBox\sounds\tuturu.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: vegeta", [[Interface\Addons\SoundBox\sounds\vegeta.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: violin", [[Interface\Addons\SoundBox\sounds\violin.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: windows", [[Interface\Addons\SoundBox\sounds\windows.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: wow", [[Interface\Addons\SoundBox\sounds\wow.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: xfiles", [[Interface\Addons\SoundBox\sounds\xfiles.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: yay", [[Interface\Addons\SoundBox\sounds\yay.ogg]])
