local LSM = LibStub("LibSharedMedia-3.0") 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "SoundBox:Ahhh", [[Interface\Addons\SoundBox\sound\ahhh.ogg]]) 
LSM:Register("sound", "SoundBox:Allahu", [[Interface\Addons\SoundBox\sound\allahu.ogg]]) 
LSM:Register("sound", "SoundBox:Babyshark", [[Interface\Addons\SoundBox\sound\babyshark.ogg]]) 
LSM:Register("sound", "SoundBox:Badum", [[Interface\Addons\SoundBox\sound\badum.ogg]]) 
LSM:Register("sound", "SoundBox:Bryant", [[Interface\Addons\SoundBox\sound\bryant.ogg]]) 
LSM:Register("sound", "SoundBox:Cabra", [[Interface\Addons\SoundBox\sound\cabra.ogg]]) 
LSM:Register("sound", "SoundBox:Careless", [[Interface\Addons\SoundBox\sound\careless.ogg]]) 
LSM:Register("sound", "SoundBox:Cato", [[Interface\Addons\SoundBox\sound\cato.ogg]]) 
LSM:Register("sound", "SoundBox:Combobreaker", [[Interface\Addons\SoundBox\sound\combobreaker.ogg]]) 
LSM:Register("sound", "SoundBox:Delfin", [[Interface\Addons\SoundBox\sound\delfin.ogg]]) 
LSM:Register("sound", "SoundBox:Digievolucion", [[Interface\Addons\SoundBox\sound\digievo.ogg]]) 
LSM:Register("sound", "SoundBox:Dolly", [[Interface\Addons\SoundBox\sound\dolly.ogg]]) 
LSM:Register("sound", "SoundBox:Dungadunga", [[Interface\Addons\SoundBox\sound\dungadunga.ogg]]) 
LSM:Register("sound", "SoundBox:Duri", [[Interface\Addons\SoundBox\sound\duri.ogg]]) 
LSM:Register("sound", "SoundBox:Ese compa", [[Interface\Addons\SoundBox\sound\ese-compa.ogg]]) 
LSM:Register("sound", "SoundBox:Finish him", [[Interface\Addons\SoundBox\sound\finish-him.ogg]]) 
LSM:Register("sound", "SoundBox:Gawr-gura-a", [[Interface\Addons\SoundBox\sound\gawr-gura-a.ogg]]) 
LSM:Register("sound", "SoundBox:Get over here", [[Interface\Addons\SoundBox\sound\get_over_here.ogg]]) 
LSM:Register("sound", "SoundBox:Gurgura", [[Interface\Addons\SoundBox\sound\gurgura.ogg]]) 
LSM:Register("sound", "SoundBox:Kala", [[Interface\Addons\SoundBox\sound\kala.ogg]]) 
LSM:Register("sound", "SoundBox:Krilin", [[Interface\Addons\SoundBox\sound\krilin.ogg]]) 
LSM:Register("sound", "SoundBox:kya", [[Interface\Addons\SoundBox\sound\kya.ogg]]) 
LSM:Register("sound", "SoundBox:Maduro chupalo", [[Interface\Addons\SoundBox\sound\maduro-chupalo.ogg]]) 
LSM:Register("sound", "SoundBox:marvel", [[Interface\Addons\SoundBox\sound\marvel.ogg]]) 
LSM:Register("sound", "SoundBox:Medusa Climax", [[Interface\Addons\SoundBox\sound\medusa-climax.ogg]]) 
LSM:Register("sound", "SoundBox:Medusa intro", [[Interface\Addons\SoundBox\sound\medusa-intro.ogg]]) 
LSM:Register("sound", "SoundBox:Migatte Fail", [[Interface\Addons\SoundBox\sound\migatte-fail.ogg]]) 
LSM:Register("sound", "SoundBox:Migatte", [[Interface\Addons\SoundBox\sound\migatte.ogg]]) 
LSM:Register("sound", "SoundBox:Modem", [[Interface\Addons\SoundBox\sound\modem.ogg]]) 
LSM:Register("sound", "SoundBox:MvC", [[Interface\Addons\SoundBox\sound\mvc.ogg]]) 
LSM:Register("sound", "SoundBox:Nani", [[Interface\Addons\SoundBox\sound\nani.ogg]]) 
LSM:Register("sound", "SoundBox:Niconi", [[Interface\Addons\SoundBox\sound\niconi.ogg]]) 
LSM:Register("sound", "SoundBox:Nos estan atacando", [[Interface\Addons\SoundBox\sound\nos-estan-atacando.ogg]]) 
LSM:Register("sound", "SoundBox:Pillarmen", [[Interface\Addons\SoundBox\sound\pillarmen.ogg]]) 
LSM:Register("sound", "SoundBox:Plusultra", [[Interface\Addons\SoundBox\sound\plusultra.ogg]]) 
LSM:Register("sound", "SoundBox:Powaa", [[Interface\Addons\SoundBox\sound\powaa.ogg]]) 
LSM:Register("sound", "SoundBox:Rezero", [[Interface\Addons\SoundBox\sound\rezero.ogg]]) 
LSM:Register("sound", "SoundBox:Rosa", [[Interface\Addons\SoundBox\sound\rosa.ogg]]) 
LSM:Register("sound", "SoundBox:Timmy", [[Interface\Addons\SoundBox\sound\timmy.ogg]]) 
LSM:Register("sound", "SoundBox:Turtle", [[Interface\Addons\SoundBox\sound\turtle.ogg]]) 
LSM:Register("sound", "SoundBox:Tuturu", [[Interface\Addons\SoundBox\sound\tuturu.ogg]]) 
LSM:Register("sound", "SoundBox:Uooooh", [[Interface\Addons\SoundBox\sound\uooooh.ogg]]) 
LSM:Register("sound", "SoundBox:Vegeta", [[Interface\Addons\SoundBox\sound\vegeta.ogg]]) 
LSM:Register("sound", "SoundBox:Windows Error", [[Interface\Addons\SoundBox\sound\windows.ogg]]) 
LSM:Register("sound", "SoundBox:Wow", [[Interface\Addons\SoundBox\sound\wow.ogg]]) 
LSM:Register("sound", "SoundBox:Yametekudasai", [[Interface\Addons\SoundBox\sound\yametekudasai.ogg]]) 
LSM:Register("sound", "SoundBox:Yare", [[Interface\Addons\SoundBox\sound\yare.ogg]]) 
LSM:Register("sound", "SoundBox:Yubarta", [[Interface\Addons\SoundBox\sound\yubarta.ogg]]) 

-- -----
--   IMG
-- -----
LSM:Register("statusbar", "SoundBox:aku-aku", [[Interface\Addons\SoundBox\img\aku-aku.tga]]) 
LSM:Register("statusbar", "SoundBox:chains", [[Interface\Addons\SoundBox\img\chains.tga]]) 
LSM:Register("statusbar", "SoundBox:darkkaiopiry", [[Interface\Addons\SoundBox\img\darkkaiopiry.tga]]) 
LSM:Register("statusbar", "SoundBox:darkkaiopiryfail", [[Interface\Addons\SoundBox\img\darkkaiopiryfail.tga]]) 
LSM:Register("statusbar", "SoundBox:gura", [[Interface\Addons\SoundBox\img\gura.tga]]) 
LSM:Register("statusbar", "SoundBox:mariano", [[Interface\Addons\SoundBox\img\mariano.tga]]) 
LSM:Register("statusbar", "SoundBox:NicoGIF1", [[Interface\Addons\SoundBox\img\NicoGIF1.tga]]) 