local LSM = LibStub("LibSharedMedia-3.0") 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "SoundBox:aiuda", [[Interface\Addons\SoundBox\sound\aiuda.ogg]]) 
LSM:Register("sound", "SoundBox:allahu", [[Interface\Addons\SoundBox\sound\allahu.ogg]]) 
LSM:Register("sound", "SoundBox:babyshark", [[Interface\Addons\SoundBox\sound\babyshark.ogg]]) 
LSM:Register("sound", "SoundBox:badum", [[Interface\Addons\SoundBox\sound\badum.ogg]]) 
LSM:Register("sound", "SoundBox:bruh", [[Interface\Addons\SoundBox\sound\bruh.ogg]]) 
LSM:Register("sound", "SoundBox:bryant", [[Interface\Addons\SoundBox\sound\bryant.ogg]]) 
LSM:Register("sound", "SoundBox:cabra", [[Interface\Addons\SoundBox\sound\cabra.ogg]]) 
LSM:Register("sound", "SoundBox:careless", [[Interface\Addons\SoundBox\sound\careless.ogg]]) 
LSM:Register("sound", "SoundBox:cato", [[Interface\Addons\SoundBox\sound\cato.ogg]]) 
LSM:Register("sound", "SoundBox:combo", [[Interface\Addons\SoundBox\sound\combo.ogg]]) 
LSM:Register("sound", "SoundBox:delfin", [[Interface\Addons\SoundBox\sound\delfin.ogg]]) 
LSM:Register("sound", "SoundBox:digievo", [[Interface\Addons\SoundBox\sound\digievo.ogg]]) 
LSM:Register("sound", "SoundBox:dolly", [[Interface\Addons\SoundBox\sound\dolly.ogg]]) 
LSM:Register("sound", "SoundBox:dungadunga", [[Interface\Addons\SoundBox\sound\dungadunga.ogg]]) 
LSM:Register("sound", "SoundBox:duri", [[Interface\Addons\SoundBox\sound\duri.ogg]]) 
LSM:Register("sound", "SoundBox:ese_compa", [[Interface\Addons\SoundBox\sound\ese_compa.ogg]]) 
LSM:Register("sound", "SoundBox:finish_him", [[Interface\Addons\SoundBox\sound\finish_him.ogg]]) 
LSM:Register("sound", "SoundBox:gawr_gura_a", [[Interface\Addons\SoundBox\sound\gawr_gura_a.ogg]]) 
LSM:Register("sound", "SoundBox:get_over_here", [[Interface\Addons\SoundBox\sound\get_over_here.ogg]]) 
LSM:Register("sound", "SoundBox:giorno", [[Interface\Addons\SoundBox\sound\giorno.ogg]]) 
LSM:Register("sound", "SoundBox:gurgura", [[Interface\Addons\SoundBox\sound\gurgura.ogg]]) 
LSM:Register("sound", "SoundBox:kala", [[Interface\Addons\SoundBox\sound\kala.ogg]]) 
LSM:Register("sound", "SoundBox:kek", [[Interface\Addons\SoundBox\sound\kek.ogg]]) 
LSM:Register("sound", "SoundBox:krillin", [[Interface\Addons\SoundBox\sound\krillin.ogg]]) 
LSM:Register("sound", "SoundBox:kya", [[Interface\Addons\SoundBox\sound\kya.ogg]]) 
LSM:Register("sound", "SoundBox:maduro_chupalo", [[Interface\Addons\SoundBox\sound\maduro_chupalo.ogg]]) 
LSM:Register("sound", "SoundBox:marvel_versus", [[Interface\Addons\SoundBox\sound\marvel_versus.ogg]]) 
LSM:Register("sound", "SoundBox:medusa_climax", [[Interface\Addons\SoundBox\sound\medusa_climax.ogg]]) 
LSM:Register("sound", "SoundBox:medusa_intro", [[Interface\Addons\SoundBox\sound\medusa_intro.ogg]]) 
LSM:Register("sound", "SoundBox:migatte", [[Interface\Addons\SoundBox\sound\migatte.ogg]]) 
LSM:Register("sound", "SoundBox:migatte_fail", [[Interface\Addons\SoundBox\sound\migatte_fail.ogg]]) 
LSM:Register("sound", "SoundBox:missioncomplete", [[Interface\Addons\SoundBox\sound\missioncomplete.ogg]]) 
LSM:Register("sound", "SoundBox:modem", [[Interface\Addons\SoundBox\sound\modem.ogg]]) 
LSM:Register("sound", "SoundBox:nani", [[Interface\Addons\SoundBox\sound\nani.ogg]]) 
LSM:Register("sound", "SoundBox:niconi", [[Interface\Addons\SoundBox\sound\niconi.ogg]]) 
LSM:Register("sound", "SoundBox:nonono", [[Interface\Addons\SoundBox\sound\nonono.ogg]]) 
LSM:Register("sound", "SoundBox:nos_estan_atacando", [[Interface\Addons\SoundBox\sound\nos_estan_atacando.ogg]]) 
LSM:Register("sound", "SoundBox:ohno", [[Interface\Addons\SoundBox\sound\ohno.ogg]]) 
LSM:Register("sound", "SoundBox:paw", [[Interface\Addons\SoundBox\sound\paw.ogg]]) 
LSM:Register("sound", "SoundBox:pillarmen", [[Interface\Addons\SoundBox\sound\pillarmen.ogg]]) 
LSM:Register("sound", "SoundBox:plusultra", [[Interface\Addons\SoundBox\sound\plusultra.ogg]]) 
LSM:Register("sound", "SoundBox:powaa", [[Interface\Addons\SoundBox\sound\powaa.ogg]]) 
LSM:Register("sound", "SoundBox:rezero", [[Interface\Addons\SoundBox\sound\rezero.ogg]]) 
LSM:Register("sound", "SoundBox:rosa", [[Interface\Addons\SoundBox\sound\rosa.ogg]]) 
LSM:Register("sound", "SoundBox:turtle", [[Interface\Addons\SoundBox\sound\turtle.ogg]]) 
LSM:Register("sound", "SoundBox:tuturu", [[Interface\Addons\SoundBox\sound\tuturu.ogg]]) 
LSM:Register("sound", "SoundBox:uoh", [[Interface\Addons\SoundBox\sound\uoh.ogg]]) 
LSM:Register("sound", "SoundBox:vamos_timmy", [[Interface\Addons\SoundBox\sound\vamos_timmy.ogg]]) 
LSM:Register("sound", "SoundBox:vcf", [[Interface\Addons\SoundBox\sound\vcf.ogg]]) 
LSM:Register("sound", "SoundBox:vegeta", [[Interface\Addons\SoundBox\sound\vegeta.ogg]]) 
LSM:Register("sound", "SoundBox:wee", [[Interface\Addons\SoundBox\sound\wee.ogg]]) 
LSM:Register("sound", "SoundBox:windows", [[Interface\Addons\SoundBox\sound\windows.ogg]]) 
LSM:Register("sound", "SoundBox:wow", [[Interface\Addons\SoundBox\sound\wow.ogg]]) 
LSM:Register("sound", "SoundBox:yametekudasai", [[Interface\Addons\SoundBox\sound\yametekudasai.ogg]]) 
LSM:Register("sound", "SoundBox:yare", [[Interface\Addons\SoundBox\sound\yare.ogg]]) 
LSM:Register("sound", "SoundBox:yubarta", [[Interface\Addons\SoundBox\sound\yubarta.ogg]]) 
LSM:Register("sound", "SoundBox:zawarudo", [[Interface\Addons\SoundBox\sound\zawarudo.ogg]]) 

-- -----
--   IMG
-- -----
LSM:Register("statusbar", "SoundBox:akuaku", [[Interface\Addons\SoundBox\img\akuaku.tga]]) 
LSM:Register("statusbar", "SoundBox:chains", [[Interface\Addons\SoundBox\img\chains.tga]]) 
LSM:Register("statusbar", "SoundBox:darkkaiopiry", [[Interface\Addons\SoundBox\img\darkkaiopiry.tga]]) 
LSM:Register("statusbar", "SoundBox:darkkaiopiryfail", [[Interface\Addons\SoundBox\img\darkkaiopiryfail.tga]]) 
LSM:Register("statusbar", "SoundBox:gura", [[Interface\Addons\SoundBox\img\gura.tga]]) 
LSM:Register("statusbar", "SoundBox:mariano", [[Interface\Addons\SoundBox\img\mariano.tga]]) 
LSM:Register("statusbar", "SoundBox:nicogif", [[Interface\Addons\SoundBox\img\nicogif.tga]]) 