local LSM = LibStub("LibSharedMedia-3.0")

-- ----------
--   SOUNDS
-- ----------
LSM:Register("sound", "|cff00FF96SoundBox|r: aleluya", [[Interface\Addons\SoundBox_Custom\sounds\aleluya.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: allahu", [[Interface\Addons\SoundBox_Custom\sounds\allahu.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: antinomy", [[Interface\Addons\SoundBox_Custom\sounds\antinomy.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: ara", [[Interface\Addons\SoundBox_Custom\sounds\ara.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: artemis", [[Interface\Addons\SoundBox_Custom\sounds\artemis.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: artemisf", [[Interface\Addons\SoundBox_Custom\sounds\artemisf.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: babyshark", [[Interface\Addons\SoundBox_Custom\sounds\babyshark.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: bhl", [[Interface\Addons\SoundBox_Custom\sounds\bhl.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: cabra", [[Interface\Addons\SoundBox_Custom\sounds\cabra.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: cato", [[Interface\Addons\SoundBox_Custom\sounds\cato.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: cris", [[Interface\Addons\SoundBox_Custom\sounds\cris.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: daniel", [[Interface\Addons\SoundBox_Custom\sounds\daniel.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: danielban", [[Interface\Addons\SoundBox_Custom\sounds\danielban.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: desik", [[Interface\Addons\SoundBox_Custom\sounds\desik.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: digievo", [[Interface\Addons\SoundBox_Custom\sounds\digievo.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: dunga", [[Interface\Addons\SoundBox_Custom\sounds\dunga.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: duri", [[Interface\Addons\SoundBox_Custom\sounds\duri.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: endouken", [[Interface\Addons\SoundBox_Custom\sounds\endouken.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: gratz", [[Interface\Addons\SoundBox_Custom\sounds\gratz.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: gurgura", [[Interface\Addons\SoundBox_Custom\sounds\gurgura.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: haha", [[Interface\Addons\SoundBox_Custom\sounds\haha.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: hahaha", [[Interface\Addons\SoundBox_Custom\sounds\hahaha.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: icarus", [[Interface\Addons\SoundBox_Custom\sounds\icarus.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: jotaeme", [[Interface\Addons\SoundBox_Custom\sounds\jotaeme.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: kala", [[Interface\Addons\SoundBox_Custom\sounds\kala.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: keydeath", [[Interface\Addons\SoundBox_Custom\sounds\keydeath.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: krillin", [[Interface\Addons\SoundBox_Custom\sounds\krillin.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: kya", [[Interface\Addons\SoundBox_Custom\sounds\kya.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: llave", [[Interface\Addons\SoundBox_Custom\sounds\llave.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: marvelf", [[Interface\Addons\SoundBox_Custom\sounds\marvelf.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: marvelv", [[Interface\Addons\SoundBox_Custom\sounds\marvelv.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: medusac", [[Interface\Addons\SoundBox_Custom\sounds\medusac.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: medusai", [[Interface\Addons\SoundBox_Custom\sounds\medusai.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: migattef", [[Interface\Addons\SoundBox_Custom\sounds\migattef.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: niconi", [[Interface\Addons\SoundBox_Custom\sounds\niconi.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: ono", [[Interface\Addons\SoundBox_Custom\sounds\ono.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: padoru", [[Interface\Addons\SoundBox_Custom\sounds\padoru.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: padresito", [[Interface\Addons\SoundBox_Custom\sounds\padresito.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: paw", [[Interface\Addons\SoundBox_Custom\sounds\paw.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: peruca", [[Interface\Addons\SoundBox_Custom\sounds\peruca.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: pillarmen", [[Interface\Addons\SoundBox_Custom\sounds\pillarmen.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: plusultra", [[Interface\Addons\SoundBox_Custom\sounds\plusultra.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: rain", [[Interface\Addons\SoundBox_Custom\sounds\rain.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: rikis", [[Interface\Addons\SoundBox_Custom\sounds\rikis.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: sharkano", [[Interface\Addons\SoundBox_Custom\sounds\sharkano.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: titanicl", [[Interface\Addons\SoundBox_Custom\sounds\titanicl.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: turtles", [[Interface\Addons\SoundBox_Custom\sounds\turtles.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: uoh", [[Interface\Addons\SoundBox_Custom\sounds\uoh.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: violinl", [[Interface\Addons\SoundBox_Custom\sounds\violinl.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: wolfis", [[Interface\Addons\SoundBox_Custom\sounds\wolfis.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: xaxs", [[Interface\Addons\SoundBox_Custom\sounds\xaxs.ogg]])
LSM:Register(
    "sound",
    "|cff00FF96SoundBox|r: yametekudasai",
    [[Interface\Addons\SoundBox_Custom\sounds\yametekudasai.ogg]]
)
LSM:Register("sound", "|cff00FF96SoundBox|r: yare", [[Interface\Addons\SoundBox_Custom\sounds\yare.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: yubarta", [[Interface\Addons\SoundBox_Custom\sounds\yubarta.ogg]])
LSM:Register("sound", "|cff00FF96SoundBox|r: zawarudo", [[Interface\Addons\SoundBox_Custom\sounds\zawarudo.ogg]])
